// <auto-generated />
using System;
using DataAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAcces.Migrations
{
    [DbContext(typeof(ApiDisneyContext))]
    [Migration("20220226214851_MigrationApiDisney")]
    partial class MigrationApiDisney
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharactersMovie", b =>
                {
                    b.Property<string>("CharacterIdCharacters")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoviesIdMovie")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CharacterIdCharacters", "MoviesIdMovie");

                    b.HasIndex("MoviesIdMovie");

                    b.ToTable("CharactersMovie");
                });

            modelBuilder.Entity("Entitys.Characters", b =>
                {
                    b.Property<string>("IdCharacters")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("IdCharacters");

                    b.ToTable("TCharacter");
                });

            modelBuilder.Entity("Entitys.Gender", b =>
                {
                    b.Property<string>("IdGender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdGender");

                    b.ToTable("TGender");
                });

            modelBuilder.Entity("Entitys.Movie", b =>
                {
                    b.Property<string>("IdMovie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderIdGender")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Qualification")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdMovie");

                    b.HasIndex("GenderIdGender");

                    b.ToTable("TMovie");
                });

            modelBuilder.Entity("Entitys.User", b =>
                {
                    b.Property<string>("IdUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdUser");

                    b.ToTable("TUser");
                });

            modelBuilder.Entity("CharactersMovie", b =>
                {
                    b.HasOne("Entitys.Characters", null)
                        .WithMany()
                        .HasForeignKey("CharacterIdCharacters")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entitys.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesIdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entitys.Movie", b =>
                {
                    b.HasOne("Entitys.Gender", null)
                        .WithMany("Movies")
                        .HasForeignKey("GenderIdGender");
                });

            modelBuilder.Entity("Entitys.Gender", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
